services:
  - type: web
    name: quality-anomaly-ia
    runtime: python

    buildCommand: pip install -r requirements.txt

    startCommand: python app_web.py

    plan: free

    envVars:
      - key: PYTHON_VERSION
        value: 3.12